services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASS}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_NAME}'
            MYSQL_USER: '${DB_USER}'
            MYSQL_PASSWORD: '${DB_PASS}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'golang-mysql:/var/lib/mysql'
        networks:
            - golang
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASS}'
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: 'phpmyadmin:5.2.1-apache'
        ports:
            - '${PHPMYADMIN_PORT:-8080}:80'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: '${DB_USER}'
            PMA_PASSWORD: '${DB_PASS}'
        depends_on:
            - mysql
        networks:
            - golang

networks:
    golang:
        driver: bridge
volumes:
    golang-mysql:
        driver: local

